<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Helpaffe.Infrastructure/Helpaffe.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Helpaffe.Api/Helpaffe.Api.csproj" />
    <ProjectReference Include="../../src/Helpaffe.Sdk/Helpaffe.Sdk.csproj" />
    <ProjectReference Include="../../examples/Helpaffe.ProductExample/Helpaffe.ProductExample.csproj" Aliases="ProductExample" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
